sudo: required

language: rust
rust:
- nightly

services:
  - postgresql
  - docker

addons:
  apt:
    packages:
    - git
    - clang
    - make
    - pkg-config
    - libssl-dev
    - capnproto
    - libsqlite3-dev
    - libpq-dev

before_install:
- rustup component add rustfmt-preview
- cargo install clippy --force
- git clone https://git.lysator.liu.se/nettle/nettle.git
- cd nettle
- git checkout 0d993096
- ./.bootstrap
- ./configure
- make
- sudo make install
- cd ..

script:
  - cargo fmt --all -- --check
  - cargo clippy
  - cargo check
  - docker-compose -f docker-compose.ci.yml up
#  - cargo test
#  - cargo build --release

cache:
  - cargo
  - ccache

before_cache:
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never