sudo: required

language: rust
rust:
- nightly

services:
  - docker

before_install:
- rustup component add rustfmt-preview

script:
  - cargo fmt --all -- --check
  - cargo clippy
  - cargo check
  - ./.docker.ci.sh
#  - cargo test
#  - cargo build --release

cache:
  - cargo
  - ccache

before_cache:
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never