language: rust
rust:
- nightly

addons:
  apt:
    packages:
    - clang
    - make
    - pkg-config
    - nettle-dev
    - libssl-dev
    - capnproto
    - libsqlite3-dev

before_script:
- rustup component add rustfmt-preview

script:
  - cargo fmt --all -- --check
  - cargo test
  - cargo check
  - cargo build
  - cargo build --release

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never